FROM docker.io/library/ubuntu:20.04
LABEL org.opencontainers.image.source https://github.com/pichuang/container-design-lab

# Set motd
ADD motd /etc/motd
RUN echo "cat /etc/motd" >> ~/.bashrc

CMD ["/bin/bash", "-l"]