FROM docker.io/library/ubuntu:20.04
LABEL org.opencontainers.image.source https://github.com/pichuang/container-design-lab

ADD motd /etc/motd
RUN echo "cat /etc/motd" >> ~/.bashrc

USER 0

CMD ["/bin/bash", "-l"]